### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by smudge202** [mykerbal/Amenschs_Mod#3]
I just thought you should no, the implications of not specifying a license are truly a nightmare. Not having a license doesn't make your software free or open source; quite the opposite. It implies a great number of restrictions, both to consumers and to _you_.

I highly recommend throwing a GPL license into the repo or reading up a bit more on it.

As with previous issue, just some friendly advice! :)

EDIT: I haven't checked, but it's probably worth checking with the software inc guy(s) what license they want modders to use incase they care?

**Comment by amensch00** [comment]
So, I just added the license ( I hope I did so).
I don't have much experience with licenses so would be great if you could just take a look if I took the right license (GPL) and applied it right :)

**Comment by smudge202** [comment]
Yup, that looks fine. You don't normally specify the `.txt` extension as a convention but I appreciate that can be tricky to achieve in windows if you don't know how, and it doesn't matter either way.

I'll close this issue as done. :+1:
